import { getFirestore, collection, addDoc, serverTimestamp, Timestamp } from 'firebase/firestore';

export type CreativeActionType = 'INJECTION' | 'CURATION' | 'STRUCTURE' | 'RESEARCH';

export interface CreativeLogEntry {
    id?: string; // Auto-generated by Firestore
    timestamp?: any; // serverTimestamp
    projectId: string;
    userId: string; // Added for security context
    component: string;
    actionType: CreativeActionType;
    description: string;
    payload: Record<string, any>;
    sessionHash?: string;
}

/**
 * Creative Audit Service
 * "The Black Box" - Records strict legal evidence of human creative will.
 */
export const CreativeAuditService = {

    /**
     * Logs a creative event to the immutable audit trail.
     * Path: projects/{projectId}/audit_log/{logId}
     */
    async logCreativeEvent(entry: Omit<CreativeLogEntry, 'id' | 'timestamp'>): Promise<string> {
        const db = getFirestore();
        const { projectId } = entry;

        // 🟢 DEBUG: Legal Evidence Real-Time View
        if (import.meta.env.DEV) {
            console.log(`⚖️ [AUDIT SIGNED] ${entry.actionType} in ${entry.component}:`, entry.description, entry.payload);
        }

        try {
            // Note: We use the root 'projects' collection as requested.
            // Ensure firestore.rules allows write access to this path for the authenticated user.
            const logRef = collection(db, 'projects', projectId, 'audit_log');

            const docRef = await addDoc(logRef, {
                ...entry,
                timestamp: serverTimestamp()
            });

            return docRef.id;
        } catch (error) {
            console.error("[CreativeAuditService] Failed to log event:", error);
            // We do not throw here to prevent blocking the user experience.
            // The audit is critical but should fail silently on the client side if network/auth issues occur,
            // or we could implement a local queue for retry. For now, just log error.
            return "";
        }
    },

    /**
     * Stub for future "Printing Press" integration.
     * Will fetch logs and format them for legal PDF generation.
     */
    async generateAuditReport(projectId: string, timeframe?: { start: Date, end: Date }): Promise<any> {
        console.log(`[Stub] Generating Audit Report for ${projectId}...`);
        return {
            status: "not_implemented",
            message: "The Printing Press is not yet online."
        };
    }
};
