import { EntityTier } from "../types/forge";

/**
 * 🛡️ UNIFIED TEMPLATE ENGINE (THE FORGE)
 * Single Source of Truth for all file generation in the Titanium Ecosystem.
 * Enforces "Seals of Power" (Frontmatter) required by the Soul Sorter.
 */

export interface AnchorTemplateData {
    name: string;
    type: 'character' | 'location' | 'faction' | 'object' | 'event' | 'concept';
    role: string; // CRITICAL: The primary Seal of Power
    description?: string;
    aliases?: string[];
    tags?: string[];
    age?: string;
    class?: string; // or Profession
    race?: string; // or Species
    faction?: string;
    status?: string; // 'active', 'deceased', etc.
    id?: string; // UUID/Hash
    project_id?: string;
    avatar?: string;
    rawBodyContent?: string; // 🟢 BUILDER OVERRIDE: Full Markdown body generated by AI
}

export interface DraftTemplateData {
    title: string;
    type: 'draft' | 'scene' | 'note';
    tags?: string[];
    summary?: string;
    content: string;
}

// Helper to safe-quote YAML strings
const safeYamlString = (str?: string): string => {
    if (!str) return "";
    // If it contains special chars, quote it
    if (str.includes(":") || str.includes("#") || str.includes("-") || str.includes("[") || str.includes("]")) {
        return `"${str.replace(/"/g, '\\"')}"`;
    }
    return str;
};

const safeYamlArray = (arr?: string[]): string => {
    if (!arr || !Array.isArray(arr) || arr.length === 0) return "[]";
    return `[${arr.filter(s => s && typeof s === 'string').map(s => `"${s.replace(/"/g, '\\"')}"`).join(", ")}]`;
};

/**
 * Generates the content for a FULL ANCHOR (Official Entity).
 * GUARANTEES: 'Role', 'Type', and standard Frontmatter.
 */
export function generateAnchorContent(data: AnchorTemplateData): string {
    const now = new Date().toISOString();

    // 1. CONSTRUCT FRONTMATTER (The Seals of Power)
    // Soul Sorter scans for: Role, Age, Class, Race, Alias, Level, Occupation, Faction.
    const frontmatter = [
        "---",
        `id: ${safeYamlString(data.id || "")}`,
        `name: ${safeYamlString(data.name)}`,
        `type: ${safeYamlString(data.type)}`,
        `role: ${safeYamlString(data.role || "Unknown")}`,
        `status: ${safeYamlString(data.status || "active")}`,
        `tier: "ANCHOR"`,
        data.age ? `age: ${safeYamlString(data.age)}` : null,
        data.class ? `class: ${safeYamlString(data.class)}` : null,
        data.race ? `race: ${safeYamlString(data.race)}` : null,
        data.faction ? `faction: ${safeYamlString(data.faction)}` : null,
        `aliases: ${safeYamlArray(data.aliases)}`,
        `tags: ${safeYamlArray(data.tags)}`,
        data.avatar ? `avatar: ${safeYamlString(data.avatar)}` : null,
        data.project_id ? `project_id: ${safeYamlString(data.project_id)}` : null,
        `created_at: "${now}"`,
        `last_updated: "${now}"`,
        "---"
    ].filter(line => line !== null).join("\n");

    // 2. CONSTRUCT BODY (Override or Default)
    if (data.rawBodyContent) {
        return `${frontmatter}\n\n${data.rawBodyContent}`;
    }

    const body = [
        `# ${data.name}`,
        "",
        `> *${(data.role || "Entidad Registrada").replace(/\n/g, ' ')}*`,
        "",
        "## 📝 Descripción",
        data.description || "Sin descripción disponible.",
        "",
        "## 🧠 Notas",
        "",
        "## 🔗 Relaciones",
        "- ",
        ""
    ].join("\n");

    return `${frontmatter}\n\n${body}`;
}

/**
 * Generates content for a DRAFT or NOTE.
 * Lighter Frontmatter, focused on content.
 */
export function generateDraftContent(data: DraftTemplateData): string {
    const now = new Date().toISOString();

    const frontmatter = [
        "---",
        `title: ${safeYamlString(data.title)}`,
        `type: ${safeYamlString(data.type)}`,
        `created_at: "${now}"`,
        `tags: ${safeYamlArray(data.tags)}`,
        data.summary ? `summary: ${safeYamlString(data.summary)}` : null,
        "---"
    ].filter(line => line !== null).join("\n");

    return `${frontmatter}\n\n# ${data.title}\n\n${data.content}`;
}
